<?php
// Path: _apps/assets/labels.php
/**
 * -----------------------------------------------------------------------------
 * Asset Tracker — Label Designer 🏷️
 * -----------------------------------------------------------------------------
 * GET-only designer/preview screen (#402). A manager picks a batch of
 * assets (checkbox list, filtered via the SAME `AssetRegister::listForSite()`
 * filters the register index uses — search + category), chooses a size
 * preset, which fields to show, whether to include a QR code, a "start
 * offset" (skip N already-used positions on a part-used physical sheet),
 * and copies-per-asset — then sees a LIVE preview built from
 * `AssetRegister::buildLabelSheets()`, the exact same rendering path
 * `labels-pdf.php` uses to produce the PDF (or its print-CSS fallback), so
 * what's previewed here is guaranteed byte-identical to what prints.
 *
 * STATE lives entirely in the querystring — this is a self-submitting GET
 * form (mirrors `loans.php`'s own filter-form convention), not a JS-driven
 * live-updating widget: changing an option and clicking "Update preview"
 * reloads this page with the new selection. This avoids re-implementing
 * `buildLabelSheets()`'s layout math a second time in JavaScript, which
 * would be exactly the kind of "two copies of the same logic that can
 * silently drift apart" this design is built to avoid (see
 * `AssetRegister::buildLabelSheets()`'s own doc). A hidden `submitted=1`
 * marker distinguishes "first load" (apply sensible defaults, and
 * pre-select a single asset from `?assetID=` when arriving from item.php's
 * "Print label" button) from "the manager already chose something" (use
 * EXACTLY what was posted, including an intentionally-empty selection).
 *
 * The actual PDF is generated by a SEPARATE POST to `labels-pdf.php` — this
 * file never writes anything; it only reads and previews. The "Generate
 * PDF" form below carries hidden inputs that echo this page's own
 * already-validated state (never raw, unfiltered $_GET) plus a CSRF token;
 * `labels-pdf.php` re-validates every one of those values again from
 * scratch regardless (see that file's own header — never trust a
 * preview's own working-out).
 *
 * GATE: manager-only (admin OR asset_manager), same as every other
 * mutating/administrative Asset Tracker screen — mirrors
 * `found-reports.php`'s `Router::renderError(403)` pattern for a GET page.
 *
 * @package   Portal\Assets
 * @author    MWBM Partners Ltd (t/a MWservices)
 * @copyright 2025-present MWBM Partners Ltd (t/a MWservices)
 * @license   All Rights Reserved
 * @version   1.0.0
 * @link      https://github.com/MWBMPartners/WebMS-Intra/issues/393
 * @link      https://github.com/MWBMPartners/WebMS-Intra/issues/402
 * -----------------------------------------------------------------------------
 */

declare(strict_types=1);

use Portal\Core\App;
use Portal\Core\AssetRegister;
use Portal\Core\Auth;
use Portal\Core\Router;
use Portal\Core\Site;

Auth::ensureSession();
Auth::requireLogin();

// 🛡️ Manager gate — admins or the asset_manager role only. See file header.
if (App::isAdmin() !== true && App::hasRole('asset_manager') !== true) {
    Router::renderError(403);
    return;
}

$siteId = Site::id();

// -----------------------------------------------------------------------------
// 📋 Parse designer state from the querystring. See file header for the
// "submitted=1" first-load-vs-resubmit distinction.
// -----------------------------------------------------------------------------
$submitted = (string) ($_GET['submitted'] ?? '') === '1';

if ($submitted === true) {
    $selectedAssetIds = array_map('intval', (array) ($_GET['assetIds'] ?? []));
} else {
    // 🔗 Arriving from item.php's "Print label" button — pre-select just
    // that one asset. Only honoured on first load; once the manager has
    // submitted their own picker choices, THOSE take over completely.
    $preselectId = (int) ($_GET['assetID'] ?? 0);
    $selectedAssetIds = $preselectId > 0 ? [$preselectId] : [];
}
$selectedAssetIds = array_values(array_unique(array_filter(
    $selectedAssetIds,
    static fn (int $id): bool => $id > 0
)));

$presetKey = (string) ($_GET['preset'] ?? 'L7160');
if (array_key_exists($presetKey, AssetRegister::LABEL_PRESETS) === false) {
    $presetKey = 'L7160';
}
$preset = AssetRegister::LABEL_PRESETS[$presetKey];
$isSmallTag = $presetKey === 'small-tag';
$cellsPerSheet = $preset['cols'] * $preset['rows'];

if ($submitted === true) {
    $fields = array_values(array_intersect((array) ($_GET['fields'] ?? []), AssetRegister::LABEL_FIELDS));
} else {
    // 🔒 Serial number OFF by default — see AssetRegister::LABEL_FIELDS's
    // own doc (labels sit physically on items; a serial number is far
    // more casually exposed there than on the logged-in register screen).
    $fields = ['name', 'assetTagCode', 'category', 'location', 'owningOrg'];
}

$qrOn = $submitted === true ? isset($_GET['qr']) : true;

$offset = max(0, (int) ($_GET['offset'] ?? 0));
$offset = min($offset, $cellsPerSheet - 1);

$copies = (int) ($_GET['copies'] ?? 1);
$copies = max(1, min(AssetRegister::MAX_LABEL_COPIES, $copies));

// -----------------------------------------------------------------------------
// 🔍 Asset picker — filtered checkbox list, reusing listForSite()'s own
// filters (search + category). $canManage is always true here (the gate
// above already required it), so confidential assets ARE included — a
// manager designing labels needs to be able to select any asset on site.
// -----------------------------------------------------------------------------
$pickerSearch     = trim((string) ($_GET['q'] ?? ''));
$pickerCategoryId = (int) ($_GET['pickerCategoryID'] ?? 0);
$pickerFilters = [];
if ($pickerSearch !== '') {
    $pickerFilters['search'] = $pickerSearch;
}
if ($pickerCategoryId > 0) {
    $pickerFilters['categoryID'] = $pickerCategoryId;
}
$pickerAssets = AssetRegister::listForSite($siteId, $pickerFilters, true);
$categories   = AssetRegister::listCategories($siteId, true);

// 🧷 Carry forward any selection that falls OUTSIDE the current filtered
// picker view. Without this, narrowing the search/category filter after
// selecting some assets would silently drop those assets from
// $selectedAssetIds on the next submit — their checkboxes simply
// wouldn't be in the DOM to resubmit. Rendered as hidden inputs
// alongside the real checkboxes below (see the form markup) so a
// selection survives filter changes across "Update preview" reloads.
$pickerAssetIdSet = array_flip(array_map('intval', array_column($pickerAssets, 'assetID')));
$carriedAssetIds = array_values(array_filter(
    $selectedAssetIds,
    static fn (int $id): bool => isset($pickerAssetIdSet[$id]) === false
));

// -----------------------------------------------------------------------------
// 🖨️ Live preview — the SAME AssetRegister::buildLabelSheets() call
// labels-pdf.php makes, so this preview and the eventual PDF can never
// disagree (see file header).
// -----------------------------------------------------------------------------
$previewAssets = count($selectedAssetIds) > 0
    ? AssetRegister::assetsForLabels($siteId, $selectedAssetIds)
    : [];
$sheets = AssetRegister::buildLabelSheets($previewAssets, $presetKey, $fields, $qrOn, $offset, $copies);

$csrf = Auth::csrfToken();

$flashMsg  = $_SESSION['flash_msg']  ?? '';
$flashType = $_SESSION['flash_type'] ?? '';
unset($_SESSION['flash_msg'], $_SESSION['flash_type']);

$pageTitle   = 'Label Designer';
$pageSection = 'assets';
$breadcrumbs = ['Dashboard' => '/', 'Assets' => '/assets', 'Label Designer' => ''];

require PORTAL_CORE . DIRECTORY_SEPARATOR . 'templates' . DIRECTORY_SEPARATOR . 'header.php';
?>

<?php if ($flashMsg !== ''): ?>
    <div class="alert alert-<?php echo htmlspecialchars($flashType !== '' ? $flashType : 'info', ENT_QUOTES, 'UTF-8'); ?>">
        <?php echo htmlspecialchars($flashMsg, ENT_QUOTES, 'UTF-8'); ?>
    </div>
<?php endif; ?>

<h1 class="mb-1"><i class="fa-solid fa-tag me-2"></i>Label designer</h1>
<p class="text-secondary mb-4">
    Pick assets, choose a sheet layout, and print QR labels. The preview below uses the
    exact same layout the generated PDF will use.
</p>

<div class="row g-4">
    <!-- 🔧 Left column — picker + options (self-submitting GET form). -->
    <div class="col-12 col-lg-6">
        <form method="get" action="/assets/labels">
            <input type="hidden" name="submitted" value="1">
            <!-- 🧷 Carry forward selections hidden by the CURRENT filter —
                 see the $carriedAssetIds PHP setup above for why this
                 matters (without it, narrowing the search/category filter
                 would silently drop earlier selections). -->
            <?php foreach ($carriedAssetIds as $cid): ?>
                <input type="hidden" name="assetIds[]" value="<?php echo (int) $cid; ?>">
            <?php endforeach; ?>

            <!-- 🔍 Picker filters -->
            <div class="card mb-3">
                <div class="card-header">
                    <h2 class="h6 mb-0">1. Choose assets</h2>
                </div>
                <div class="card-body">
                    <?php if (count($selectedAssetIds) > 0): ?>
                        <p class="small text-muted">
                            <?php echo count($selectedAssetIds); ?> asset(s) selected in total
                            <?php if (count($carriedAssetIds) > 0): ?>
                                (<?php echo count($carriedAssetIds); ?> hidden by the current filter, but still selected)
                            <?php endif; ?>.
                        </p>
                    <?php endif; ?>
                    <div class="row g-2 mb-3">
                        <div class="col-7">
                            <input type="text" class="form-control form-control-sm" name="q"
                                   placeholder="Search name/serial/tag&hellip;"
                                   value="<?php echo htmlspecialchars($pickerSearch, ENT_QUOTES, 'UTF-8'); ?>">
                        </div>
                        <div class="col-5">
                            <select class="form-select form-select-sm" name="pickerCategoryID">
                                <option value="0">All categories</option>
                                <?php foreach ($categories as $cat): ?>
                                    <option value="<?php echo (int) $cat['categoryID']; ?>"
                                        <?php echo $pickerCategoryId === (int) $cat['categoryID'] ? ' selected' : ''; ?>>
                                        <?php echo htmlspecialchars((string) $cat['categoryName'], ENT_QUOTES, 'UTF-8'); ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <?php if (count($pickerAssets) === 0): ?>
                        <p class="text-muted small mb-0">No assets match this filter.</p>
                    <?php else: ?>
                        <div class="border rounded p-2" style="max-height: 260px; overflow-y: auto;">
                            <?php foreach ($pickerAssets as $pa):
                                $paId = (int) $pa['assetID'];
                                $paChecked = in_array($paId, $selectedAssetIds, true) === true;
                                $paMeta = trim(
                                    ($pa['categoryName'] !== null ? (string) $pa['categoryName'] : '')
                                    . ($pa['assetTagCode'] !== null && (string) $pa['assetTagCode'] !== '' ? ' &middot; ' . (string) $pa['assetTagCode'] : '')
                                );
                            ?>
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="assetIds[]"
                                           value="<?php echo $paId; ?>" id="pa<?php echo $paId; ?>"
                                           <?php echo $paChecked === true ? ' checked' : ''; ?>>
                                    <label class="form-check-label small" for="pa<?php echo $paId; ?>">
                                        <?php echo htmlspecialchars((string) $pa['name'], ENT_QUOTES, 'UTF-8'); ?>
                                        <?php if ($paMeta !== ''): ?>
                                            <span class="text-muted">&mdash; <?php echo htmlspecialchars($paMeta, ENT_QUOTES, 'UTF-8'); ?></span>
                                        <?php endif; ?>
                                    </label>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <!-- 📐 Sheet + field options -->
            <div class="card mb-3">
                <div class="card-header"><h2 class="h6 mb-0">2. Layout &amp; content</h2></div>
                <div class="card-body">
                    <label class="form-label fw-semibold small">Label size</label>
                    <?php foreach (AssetRegister::LABEL_PRESETS as $key => $def): ?>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="preset"
                                   value="<?php echo htmlspecialchars($key, ENT_QUOTES, 'UTF-8'); ?>"
                                   id="preset<?php echo htmlspecialchars($key, ENT_QUOTES, 'UTF-8'); ?>"
                                   <?php echo $presetKey === $key ? ' checked' : ''; ?>>
                            <label class="form-check-label small" for="preset<?php echo htmlspecialchars($key, ENT_QUOTES, 'UTF-8'); ?>">
                                <?php echo htmlspecialchars($def['label'], ENT_QUOTES, 'UTF-8'); ?>
                            </label>
                        </div>
                    <?php endforeach; ?>

                    <label class="form-label fw-semibold small mt-3">Fields to show</label>
                    <?php if ($isSmallTag === true): ?>
                        <p class="small text-muted mb-2">
                            The small tag preset always shows the QR code plus the asset tag code only
                            &mdash; there isn't room for more on a 38&times;21mm label.
                        </p>
                    <?php endif; ?>
                    <?php foreach (AssetRegister::LABEL_FIELDS as $fieldKey): ?>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" name="fields[]"
                                   value="<?php echo htmlspecialchars($fieldKey, ENT_QUOTES, 'UTF-8'); ?>"
                                   id="field<?php echo htmlspecialchars($fieldKey, ENT_QUOTES, 'UTF-8'); ?>"
                                   <?php echo in_array($fieldKey, $fields, true) === true ? ' checked' : ''; ?>
                                   <?php echo $isSmallTag === true ? ' disabled' : ''; ?>>
                            <label class="form-check-label small" for="field<?php echo htmlspecialchars($fieldKey, ENT_QUOTES, 'UTF-8'); ?>">
                                <?php echo htmlspecialchars(AssetRegister::LABEL_FIELD_LABELS[$fieldKey], ENT_QUOTES, 'UTF-8'); ?>
                            </label>
                        </div>
                    <?php endforeach; ?>
                    <p class="small text-muted mt-1 mb-0">
                        <i class="fa-solid fa-shield-halved me-1"></i>
                        Serial number is off by default &mdash; labels sit physically on the item, so anyone who
                        picks it up can read what's printed. Only enable it if that's acceptable for these assets.
                    </p>

                    <div class="form-check form-switch mt-3">
                        <input class="form-check-input" type="checkbox" role="switch" name="qr" value="1"
                               id="qrToggle"<?php echo $qrOn === true ? ' checked' : ''; ?>>
                        <label class="form-check-label small" for="qrToggle">Include QR code (links to the asset's public page)</label>
                    </div>

                    <div class="row g-2 mt-3">
                        <div class="col-6">
                            <label class="form-label small" for="offset">Start offset (skip used positions)</label>
                            <input type="number" class="form-control form-control-sm" name="offset" id="offset"
                                   min="0" max="<?php echo $cellsPerSheet - 1; ?>" value="<?php echo $offset; ?>">
                        </div>
                        <div class="col-6">
                            <label class="form-label small" for="copies">Copies per asset</label>
                            <input type="number" class="form-control form-control-sm" name="copies" id="copies"
                                   min="1" max="<?php echo AssetRegister::MAX_LABEL_COPIES; ?>" value="<?php echo $copies; ?>">
                        </div>
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-outline-primary btn-sm">
                <i class="fa-solid fa-rotate me-1"></i>Update preview
            </button>
        </form>
    </div>

    <!-- 🖼️ Right column — live preview + Generate PDF. -->
    <div class="col-12 col-lg-6">
        <div class="card mb-3">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h2 class="h6 mb-0">3. Preview &amp; generate</h2>
            </div>
            <div class="card-body">
                <?php if (count($previewAssets) === 0): ?>
                    <div class="alert alert-info mb-0">
                        <i class="fa-solid fa-circle-info me-2"></i>
                        Select at least one asset on the left to preview labels.
                    </div>
                <?php else: ?>
                    <p class="small text-muted">
                        <strong><?php echo (int) $sheets['labelCount']; ?></strong> label(s) across
                        <strong><?php echo (int) $sheets['sheetCount']; ?></strong> sheet(s)
                        <?php if ($offset > 0): ?>
                            (<?php echo $offset; ?> position(s) skipped at the start of the first sheet)
                        <?php endif; ?>.
                    </p>

                    <form method="post" action="/assets/labels-pdf" class="mb-3">
                        <input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf, ENT_QUOTES, 'UTF-8'); ?>">
                        <?php foreach ($selectedAssetIds as $sid): ?>
                            <input type="hidden" name="assetIds[]" value="<?php echo (int) $sid; ?>">
                        <?php endforeach; ?>
                        <input type="hidden" name="preset" value="<?php echo htmlspecialchars($presetKey, ENT_QUOTES, 'UTF-8'); ?>">
                        <?php foreach ($fields as $f): ?>
                            <input type="hidden" name="fields[]" value="<?php echo htmlspecialchars($f, ENT_QUOTES, 'UTF-8'); ?>">
                        <?php endforeach; ?>
                        <input type="hidden" name="qr" value="<?php echo $qrOn === true ? '1' : '0'; ?>">
                        <input type="hidden" name="offset" value="<?php echo $offset; ?>">
                        <input type="hidden" name="copies" value="<?php echo $copies; ?>">
                        <button type="submit" class="btn btn-success btn-sm">
                            <i class="fa-solid fa-file-pdf me-1"></i>Generate PDF
                        </button>
                    </form>

                    <!-- 📄 Preview — uses the SAME CSS/HTML buildLabelSheets()
                         returns; labels-pdf.php embeds this identically into
                         its dompdf/print-CSS output. Raw echo, not
                         htmlspecialchars() — the content is already escaped
                         field-by-field inside buildLabelSheets() itself. -->
                    <style><?php echo $sheets['css']; ?></style>
                    <div style="overflow: auto; max-width: 100%; border: 1px solid #dee2e6; padding: .5rem; background: #e9ecef;">
                        <?php echo $sheets['html']; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<p class="mt-3"><a href="/assets" class="btn btn-outline-secondary btn-sm"><i class="fa-solid fa-arrow-left me-1"></i>Back to Asset Tracker</a></p>

<?php require PORTAL_CORE . DIRECTORY_SEPARATOR . 'templates' . DIRECTORY_SEPARATOR . 'footer.php'; ?>
